#!/bin/bash


# https://www.howtogeek.com/410442/how-to-display-the-date-and-time-in-the-linux-terminal-and-use-it-in-bash-scripts/
function pretty_datetime() {
  date +"%A %d %B %X"
}

echo "placeholder $(pretty_datetime)"

#TODO update only every 15s, and don't show the the seconds in the time
#TODO take the output of the below, parse it, and echo how long til next meeting in the bar
#TODO error handling: no auth, can't format output, and so on
#TODO symlink this file to ~/.config/tmux/calendar_status_right

#next_event=$(gcalcli --nocolor agenda --nostarted --tsv | head -2 | tail -1)
#
#echo $next_event
