#! /bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

source "$SCRIPT_DIR/fatboi/coloured_echos.sh"

function configure_bashrc {
  touch ~/.bashrc
  source_bashrc_additions="source ~/src/dev_setup/bashrc_cygwin"
  if [ `grep -c "$source_bashrc_additions" ~/.bashrc` -eq 0 ]; then
    echo "$source_bashrc_additions" >> ~/.bashrc
  fi
}

function configure_vim {
  touch ~/.vimrc
  pushd .
  mkdir -p ~/.vim/colors
  cd ~/.vim/colors
  if [ ! -f solarized.vim ]; then
    curl https://raw.githubusercontent.com/altercation/vim-colors-solarized/master/colors/solarized.vim --output solarized.vim
  fi
  if [ ! -f ~/.vim/autoload/plug.vim ]; then
    mkdir -p ~/.vim/autoload
    pushd .
    cd ~/.vim/autoload
    curl https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim --output plug.vim
    popd
  fi
  popd
  vim +'PlugInstall --sync' +qa
}

setup_ssh_bash_autocomplete() {
  echo_in_magenta "ssh autocomplete - checking"

  path=/etc/bash_completion.d/ssh

  dest=$(realpath ~/src/dev_setup/fatboi/ssh_bash_autocomplete)
  link=$(readlink $path 2>&1)

  if [ $? -eq 0 ] && [ "$link" = "$dest" ]; then
    echo_in_green "ssh autocomplete - already in place!"
  else
    echo_in_magenta "ssh autocomplete - setting up..."
    echo $dest
    echo $link
    ln -sf $dest $path

    if [ $? -eq 0 ]; then
      echo_in_green "ssh autocomplete - setup complete!"
    else
      echo_in_red "ssh autocomplete - setup failed"
    fi
  fi
}

configure_bashrc
configure_vim
setup_ssh_bash_autocomplete
