#!/bin/bash

ssh_attempt=1

echo_overwriting_last_line() {
  echo -e "\e[1A\e[K$1"
}

ssh_retry() {
  ssh_args=$1
  ssh -o ConnectTimeout=1 -Y "$ssh_args" 2> /dev/null
  result=$?
  if [[ $result == 0 ]]; then
    exit 0
  elif [[ $result == 130 ]]; then
    exit 0
  else
    if [[ $ssh_attempt == 1 ]]; then
      echo "Attempting to ssh $ssh_args...(attempt $ssh_attempt)"
    else
      echo_overwriting_last_line "Attempting to ssh $ssh_args...(attempt $ssh_attempt)"
    fi
    ssh_attempt=$(expr $ssh_attempt + 1)
    ssh_retry
  fi
}

ssh_retry $1
