#!/bin/bash

which noip-duc >/dev/null

if [[ $? -ne 0 ]]; then
  wget --content-disposition https://www.noip.com/download/linux/latest
  tar xf noip-duc_3.1.1.tar.gz
  sudo apt install ./noip-duc_3.1.1/binaries/noip-duc_3.1.1_amd64.deb -y
  rm -rf noip-duc/3.1.1*
fi




#cd /home/$USER/noip-duc_3.1.1/binaries && sudo apt install ./noip-duc_3.1.1_amd64.deb
