#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

set -a
source $SCRIPT_DIR/.noip_env_vars
set +a

tmux new-session -d -s noip 'noip-duc -g all.ddnskey.com'
