#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

source "$SCRIPT_DIR/coloured_echos.sh"

add_line_if_missing() {
  grep -E "^$1$" $2 >/dev/null
  if [[ $? -eq 0 ]]; then
    echo "$1 - $2 - Already set"
  else
    echo "$1" >> $2
    eval $"$3"=true
    echo "$1 - $2 - Set"
  fi
}

sudo_apt_install_packages() {
  # https://elixirforum.com/t/wsl-mix-deps-get-the-application-crypto-could-not-be-found/57916/7
  # libssl-dev needed for erlang?
  packages="build-essential libreadline-dev unzip curl wget gcc tmux fzf tree libssl-dev fontconfig ripgrep fuse libfuse-dev lua5.1 vim autoconf erlang elixir"
  echo_in_magenta "Running 'sudo apt install $packages -y'"
  eval "sudo apt install $packages -y"
}

sudo_apt_update() {
  echo_in_magenta "Running sudo apt update"
  sudo apt update
}

add_bashrc_additions() {
  bashrc_line="source $SCRIPT_DIR/bashrc_additions"
  echo_in_magenta "bashrc additions - checking"
  if [ `grep -c "$bashrc_line" ~/.bashrc` -eq 0 ]; then
    echo_in_magenta "bashrc additions - adding them.."
    echo "$bashrc_line" >> ~/.bashrc
    if [[ $? -eq 0 ]]; then
      echo_in_green "bashrc additions - added successfully"
    else
      echo_in_ren "bashrc additions - failed"
      exit 1
    fi
  else
    echo_in_green "bashrc additions - they're already added"
  fi
}

configure_tmux() {
  echo_in_magenta "tmux config symlink - checking"
  if [ -d ~/src/dev_setup ]; then
    dest=$(realpath $SCRIPT_DIR/.tmux.conf)
    link=$(readlink ~/.tmux.conf 2>&1)
    if [ $? -eq 0 ]; then
      if [ "$link" = "$dest" ]; then
        echo_in_green "tmux config symlink - already in place!"
      else
        echo_in_red "tmux config symlink - broken!"
        exit 1
      fi
    else
      ln -sf $dest ~/.tmux.conf
      if [ $? -eq 0 ]; then
        echo_in_green "tmux config symlink - created successfully!"
      else
        echo_in_red "tmux config symlink - creation failed!"
        exit 1
      fi
    fi
  else
    echo_in_red "tmux config symlink - ~/src/dev_setup does not exist, so bailing"
    exit 1
  fi
}

install_zoxide() {
  echo_in_magenta "zoxide - checking"
  which zoxide >/dev/null
  if [[ $? -eq 0 ]]; then
    echo_in_green "zoxide - already installed"
    zoxide --version
  else
    echo_in_magenta "zoxide - installing.."
    curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh
  fi
}

install_mob() {
  echo_in_magenta "mob - checking"
  if [ -d ~/src/mob ]; then
    echo_in_green "mob - already in place!"
  else
    echo_in_magenta "mob - git cloning..."
    git clone git@github.com:mbernerslee/mob.git ~/src/mob
    if [ $? -eq 0 ]; then
      echo_in_magenta "mob - installing..."
      cd ~/src/mob
      ./install
      if [ $? -eq 0 ]; then
        echo_in_green "mob - installed successfully!"
      else
        echo_in_red "mob - install failed"
      fi
    else
      echo_in_red "mob - failed"
    fi
  fi
}

# https://dev.to/ahmedmusallam/how-to-autocomplete-ssh-hosts-1hob
setup_ssh_bash_autocomplete() {
  echo_in_magenta "ssh autocomplete - checking"

  path=/etc/bash_completion.d/ssh

  dest=$(realpath $SCRIPT_DIR/../fatboi/ssh_bash_autocomplete)
  link=$(readlink $path 2>&1)

  if [ $? -eq 0 ] && [ "$link" = "$dest" ]; then
    echo_in_green "ssh autocomplete - already in place!"
  else
    echo_in_magenta "ssh autocomplete - setting up..."
    sudo ln -sf $dest $path

    if [ $? -eq 0 ]; then
      echo_in_green "ssh autocomplete - setup complete!"
    else
      echo_in_red "ssh autocomplete - setup failed"
    fi
  fi
}

install_minimal_vimrc_dependencies() {
  pushd .
  mkdir -p ~/.vim/colors
  cd ~/.vim/colors
  if [ ! -f solarized.vim ]; then
    wget https://raw.githubusercontent.com/altercation/vim-colors-solarized/master/colors/solarized.vim
  fi
  if [ ! -f ~/.vim/autoload/plug.vim ]; then
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  fi
  popd

  sudo apt-get install ack -y
  vim +'PlugInstall --sync' +qa
}

symlink_minimal_vimrc() {
  echo_in_magenta "checking vimrc symlink"

  path=~/.vimrc

  dest=$(realpath ~/src/dev_setup/.minimal_vimrc)
  link=$(readlink $path 2>&1)

  if [ $? -eq 0 ] && [ "$link" = "$dest" ]; then
    echo_in_green "vimrc symlink - already in place!"
  else
    echo_in_magenta "vimrc symlink - setting up..."
    sudo ln -sf $dest $path

    if [ $? -eq 0 ]; then
      echo_in_green "vimrc symlink - setup complete!"
    else
      echo_in_red "vimrc symlink - setup failed"
      exit 1
    fi
  fi
}

symlink_tool_versions() {
  echo_in_magenta "checking vimrc symlink"

  path=~/.vimrc

  dest=$(realpath ~/src/dev_setup/.minimal_vimrc)
  link=$(readlink $path 2>&1)

  if [ $? -eq 0 ] && [ "$link" = "$dest" ]; then
    echo_in_green "vimrc symlink - already in place!"
  else
    echo_in_magenta "vimrc symlink - setting up..."
    sudo ln -sf $dest $path

    if [ $? -eq 0 ]; then
      echo_in_green "vimrc symlink - setup complete!"
    else
      echo_in_red "vimrc symlink - setup failed"
      exit 1
    fi
  fi
}

sudo_apt_update
sudo_apt_install_packages
install_minimal_vimrc_dependencies
symlink_minimal_vimrc
install_zoxide
configure_tmux
add_bashrc_additions
install_mob
setup_ssh_bash_autocomplete
